name: Inciteful-CI

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Building and Deploying
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install caprover
        run: npm install -g caprover
      - name: Caprover Deploy Plugin
        run: caprover deploy -h 'https://captain.cap.weishuhn.net' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'master' -a 'inciteful-chatgpt-plugin'
      
